import{a as S,S as q,i as c}from"./assets/vendor-DqB7j7Ix.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const P="51414805-32578d6fb6ee3cb7948c7bdf3";async function m(a,t=1){const{data:o}=await S("https://pixabay.com/api/",{params:{key:P,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}});return o}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),f=document.querySelector(".js-load-more");let l=null;function g(a){const t=a.map(({webformatURL:o,largeImageURL:i,tags:e,likes:r,views:s,comments:L,downloads:w})=>`<li class="gallery-item">
            <a href="${i}">
                <img src="${o}" alt="${e}"/>
            </a>
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${L}</p>
        <p><b>Downloads:</b> ${w}</p>
        </li >
        `).join("");p.insertAdjacentHTML("beforeend",t),f.classList.replace("load-more-hidden","load-more"),l?l.refresh():l=new q(".gallery a",{captionsData:"alt",captionDelay:250})}function v(){p.innerHTML=""}function y(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}function M(){f.classList.remove("load-more-hidden")}function d(){f.classList.add("load-more-hidden")}const $=document.querySelector(".form"),B=document.querySelector(".search-input"),H=document.querySelector(".js-load-more"),O=15;let u="",n=1,R=0,j=0;$.addEventListener("submit",x);H.addEventListener("click",D);async function x(a){a.preventDefault();const t=B.value.trim();if(!t){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}u=t,n=1,v(),d(),y();try{const o=await m(u,n=1);R=o.totalHits;const i=Math.ceil(o.totalHits/O);if(o.hits.length===0){c.info({message:"No images found. Try a different search term.",position:"topRight"});return}g(o.hits),n<i?M():(d(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}}async function D(){n++,y();try{const a=await m(u,n);g(a.hits),n>=j&&d();const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({left:0,top:o*2,behavior:"smooth"})}}catch(a){c.error({message:a.message,position:"topRight"})}finally{b()}}
//# sourceMappingURL=index.js.map
